# Generated by Django 4.2.7 on 2023-11-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='commit',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='parentResourceId',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='resourceId',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='spanId',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='traceId',
            field=models.CharField(max_length=1000),
        ),
    ]
